version: "3.9"

services:
  llama:
    build:
      context: .
      dockerfile: Dockerfiles/LlamaCPPDockerfile
    container_name: llama
    environment:
      - NVIDIA_VISIBLE_DEVICES=0  # Ensures only GPU 0 is visible
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 24G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['5'] # Keep quoting for DEVICE_ID
              capabilities: [gpu]
    networks:
      - local_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/health | grep 200"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s

  proxy:
    build:
      context: .
      dockerfile: Dockerfiles/ProxyDockerfile
    container_name: proxy
    ports:
      - "8000:8000"
    env_file:
      - .env
#    depends_on:
#      llama:
#        condition: service_healthy
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

